batch_size: 64
epochs: 200
exp_name: mnist_fixed
labels: ./data/mnist_svhn/labels.pkl
lr: 1e-3
mixing: moe
growtype: neurons
initial_latent_n: 5
initial_patience: 5
adaptive: 0
n_latents: 20
obj: elbo
optimizer: adam
exp_classes: 10
pre_trained: null
seed: 1
beta: 1
viz_freq: 10
test_split: 0.1
dataset_name: mnist_svhn
modality_1:
  decoder: MNIST
  encoder: MNIST
  mod_type: mnist
  growtype: neurons
  recon_loss: bce
  path: ./data/mnist_svhn/mnist
