batch_size: 16
epochs: 200
exp_name: sprites_fixed
lr: 1e-3
labels:
mixing: moe
growtype: neurons
initial_latent_n: 5
initial_patience: 5
adaptive: 0
n_latents: 13
obj: elbo
optimizer: adam
exp_classes: 9
pre_trained: null
seed: 2
beta: 1
viz_freq: 10
test_split: 0.1
dataset_name: sprites
modality_1:
  decoder: VideoGPT
  encoder: VideoGPT
  mod_type: frames
  growtype: neurons
  recon_loss:  bce
  path: ./data/sprites
  test_datapath:
